name: Lint & Test
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Lint & Test
    strategy:
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - if: matrix.node-version == 22
        run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build
